stages:
  - build
  - release
  - deploy

before_script:
  - docker login -u $REGISTRY_LOGIN -p $REGISTRY_PASSWORD docker-registry.green-light.com

after_script:
  - docker system prune -f

build:
  stage: build
  script:
    - docker build --build-arg COMPOSER_ARG=--no-dev --build-arg BOWER_ARG=--production -t docker-registry.green-light.com/green-light/gls-web:latest -f ./docker/Dockerfile .
  only:
    - docker

release:
  stage: release
  script:
    - docker push docker-registry.green-light.com/green-light/gls-web:latest
  only:
    - docker


deploy:
  stage: deploy
  script:
    - docker pull docker-registry.green-light.com/green-light/gls-web:latest
    - docker service update --force --image=docker-registry.green-light.com/green-light/gls-web:latest gls-web_web
    - docker system prune -f


