stages:
  - build
  - release

build:
  stage: build
  script:
    - docker build --build-arg COMPOSER_ARG=--no-dev --build-arg BOWER_ARG=--production -t docker-registry.green-light.com/green-light/gls-web:latest -f ./docker/Dockerfile .
  only:
    - docker

release:
  stage: release
  script:
    - docker system prune -f
    - docker login -u $REGISTRY_LOGIN -p $REGISTRY_PASSWORD docker-registry.green-light.com
    - docker push docker-registry.green-light.com/green-light/gls-web:latest
  only:
    - docker
