image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - deploy

before_script:
    - IMAGE_NAME=$(date +%y%m%d)-$(echo $CI_COMMIT_SHA | cut -c 1-7)
    - docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWORD" docker-registry.green-light.com
    - DEV_TAG="docker-registry.green-light.com/green-light/green-light.com:latest-dev"
    - PROD_TAG="docker-registry.green-light.com/green-light/green-light.com:latest"

build-dev:
  stage: build
  script:
    #- docker login -u "green-light-ci" -p "$CI_JOB_TOKEN" registry.green-light.com
    - docker pull $DEV_TAG || true
    - docker build --cache-from "$DEV_TAG" --tag "$DEV_TAG" .
    - docker push "$DEV_TAG"
  tags:
    - docker
    - vshosting-cluster
  only:
    - dev

deploy-dev:
  stage: deploy
  script:
    - docker pull "$DEV_TAG"
    - docker service update --with-registry-auth --image $(docker inspect --type image --format '{{index .RepoDigests 0}}' $DEV_TAG) green-light-dev_web
  tags:
    - docker
    - vshosting-cluster
  only:
    - dev

build-prod:
  stage: build
  script:
    - docker build --pull -t "$PROD_TAG" .
    - docker push "$PROD_TAG"
  tags:
    - docker
    - vshosting-cluster
  only:
    - master

deploy-prod:
  stage: deploy
  script:
    - docker pull "$PROD_TAG"
    - docker service update --with-registry-auth --image $(docker inspect --type image --format '{{index .RepoDigests 0}}' $PROD_TAG) green-light-prod_web
  tags:
    - docker
    - vshosting-cluster
  only:
    - master