# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "app/**/*.html"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"
  # Path to dev folder
  dev: "app"
  # Path to clean up dev files
  cleanup: "dist/**/*"
  # Paths to static assets that aren't CSS, or JavaScript
  assets:
    - "app/**/*"
    - "!app/bower_components"
    - "!app/bower_components/**/*"
    - "!app/assets/{js,scss}"
    - "!app/assets/{js,scss}/**/*"

  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "app/bower_components/foundation-sites/scss"
    # -- ADD CUSTOM PLUGINS SASS HERE --

  # Paths to JavaScript libraries, which are compined into one file
  javascript:
    # Libraries requried by Foundation
    - "app/bower_components/jquery/dist/jquery.js"
    - "app/bower_components/what-input/what-input.js"
    # Core Foundation files
    - "app/bower_components/foundation-sites/dist/plugins/foundation.core.js"
    - "app/bower_components/foundation-sites/dist/plugins/foundation.util.*.js"
    # Individual Foundation components
    # If you aren't using a component, just remove it from the list
    - "app/bower_components/foundation-sites/dist/plugins/foundation.abide.js"
    - "app/bower_components/foundation-sites/dist/plugins/foundation.accordion.js"
    - "app/bower_components/foundation-sites/dist/plugins/foundation.accordionMenu.js"
    - "app/bower_components/foundation-sites/dist/plugins/foundation.drilldown.js"
    - "app/bower_components/foundation-sites/dist/plugins/foundation.dropdown.js"
    - "app/bower_components/foundation-sites/dist/plugins/foundation.dropdownMenu.js"
    - "app/bower_components/foundation-sites/dist/plugins/foundation.equalizer.js"
    - "app/bower_components/foundation-sites/dist/plugins/foundation.interchange.js"
    - "app/bower_components/foundation-sites/dist/plugins/foundation.magellan.js"
    - "app/bower_components/foundation-sites/dist/plugins/foundation.offcanvas.js"
    - "app/bower_components/foundation-sites/dist/plugins/foundation.orbit.js"
    - "app/bower_components/foundation-sites/dist/plugins/foundation.responsiveMenu.js"
    - "app/bower_components/foundation-sites/dist/plugins/foundation.responsiveToggle.js"
    - "app/bower_components/foundation-sites/dist/plugins/foundation.reveal.js"
    - "app/bower_components/foundation-sites/dist/plugins/foundation.slider.js"
    - "app/bower_components/foundation-sites/dist/plugins/foundation.sticky.js"
    - "app/bower_components/foundation-sites/dist/plugins/foundation.tabs.js"
    - "app/bower_components/foundation-sites/dist/plugins/foundation.toggler.js"
    - "app/bower_components/foundation-sites/dist/plugins/foundation.tooltip.js"
    # Paths to your own project code are here
    - "app/assets/js/**/!(app).js"
    - "app/assets/js/app.js"
    # -- ADD CUSTOM PLUGINS JS HERE --
    - "app/assets/js/topbar.js"
    - "app/assets/js/smooth-scroll.js"