version: "3.4"

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: gls-web
    ports:
      - 8080:80
    environment:
      - DEBUG=1
    volumes:
      - "../:/var/www"